"""empty message

Revision ID: 6d5dc54df253
Revises: 21c74760d462
Create Date: 2021-07-29 20:47:39.898711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5dc54df253'
down_revision = '21c74760d462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(length=64), nullable=True))
    op.drop_column('book', 'about')
    op.drop_column('book', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('num', sa.INTEGER(), nullable=True))
    op.add_column('book', sa.Column('about', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
